[2025-08-02T14:09:31.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-02T14:09:31.361+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_etl_pipeline.create_table manual__2025-08-02T14:09:29.265146+00:00 [queued]>
[2025-08-02T14:09:31.368+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_etl_pipeline.create_table manual__2025-08-02T14:09:29.265146+00:00 [queued]>
[2025-08-02T14:09:31.368+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-02T14:09:31.378+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_table> on 2025-08-02 14:09:29.265146+00:00
[2025-08-02T14:09:31.382+0000] {standard_task_runner.py:64} INFO - Started process 127 to run task
[2025-08-02T14:09:31.385+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'transaction_etl_pipeline', 'create_table', 'manual__2025-08-02T14:09:29.265146+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmplfhw8ewl']
[2025-08-02T14:09:31.386+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask create_table
[2025-08-02T14:09:31.418+0000] {task_command.py:426} INFO - Running <TaskInstance: transaction_etl_pipeline.create_table manual__2025-08-02T14:09:29.265146+00:00 [running]> on host f89c4ed376bf
[2025-08-02T14:09:31.477+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='DataTeam' AIRFLOW_CTX_DAG_ID='transaction_etl_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T14:09:29.265146+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T14:09:29.265146+00:00'
[2025-08-02T14:09:31.478+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-02T14:09:31.479+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-02T14:09:31.479+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/etl && python create_table.py']
[2025-08-02T14:09:31.489+0000] {subprocess.py:86} INFO - Output:
[2025-08-02T14:09:31.544+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/etl/create_table.py': [Errno 2] No such file or directory
[2025-08-02T14:09:31.547+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-02T14:09:31.548+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-02T14:09:31.558+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-02T14:09:31.560+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=transaction_etl_pipeline, task_id=create_table, run_id=manual__2025-08-02T14:09:29.265146+00:00, execution_date=20250802T140929, start_date=20250802T140931, end_date=20250802T140931
[2025-08-02T14:09:31.568+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task create_table (Bash command failed. The command returned a non-zero exit code 2.; 127)
[2025-08-02T14:09:31.596+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-02T14:09:31.614+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-02T14:09:31.615+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
