[2025-08-02T14:19:32.639+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-02T14:19:32.656+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_etl_pipeline.create_table scheduled__2025-08-01T00:00:00+00:00 [queued]>
[2025-08-02T14:19:32.663+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_etl_pipeline.create_table scheduled__2025-08-01T00:00:00+00:00 [queued]>
[2025-08-02T14:19:32.664+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-08-02T14:19:32.675+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_table> on 2025-08-01 00:00:00+00:00
[2025-08-02T14:19:32.679+0000] {standard_task_runner.py:64} INFO - Started process 319 to run task
[2025-08-02T14:19:32.682+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'transaction_etl_pipeline', 'create_table', 'scheduled__2025-08-01T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpjwlykn9b']
[2025-08-02T14:19:32.683+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask create_table
[2025-08-02T14:19:32.719+0000] {task_command.py:426} INFO - Running <TaskInstance: transaction_etl_pipeline.create_table scheduled__2025-08-01T00:00:00+00:00 [running]> on host f89c4ed376bf
[2025-08-02T14:19:32.775+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='DataTeam' AIRFLOW_CTX_DAG_ID='transaction_etl_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-01T00:00:00+00:00'
[2025-08-02T14:19:32.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-02T14:19:32.777+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-02T14:19:32.777+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/etl && python create_table.py']
[2025-08-02T14:19:32.787+0000] {subprocess.py:86} INFO - Output:
[2025-08-02T14:19:32.836+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/etl/create_table.py': [Errno 2] No such file or directory
[2025-08-02T14:19:32.839+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-02T14:19:32.840+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-02T14:19:32.846+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-02T14:19:32.849+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=transaction_etl_pipeline, task_id=create_table, run_id=scheduled__2025-08-01T00:00:00+00:00, execution_date=20250801T000000, start_date=20250802T141932, end_date=20250802T141932
[2025-08-02T14:19:32.859+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task create_table (Bash command failed. The command returned a non-zero exit code 2.; 319)
[2025-08-02T14:19:32.893+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-02T14:19:32.918+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-02T14:19:32.921+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
